import {
  BarChart3,
  Database,
  Flame,
  Landmark,
  Map,
  MapPin,
  Network,
  Target,
  UserCheck,
  Users,
} from "lucide-react";
import type { ForceNode } from "./types";

export const forceMapLevels: ForceNode[][] = [
  [
    {
      id: "candidato",
      title: "Candidato",
      subtitle: "Decisão, narrativa e priorização política.",
      icon: Target,
      tone: "slate",
      count: "1",
      countLabel: "núcleo",
      status: "Ativo",
      summary: "Visão consolidada da operação, conectando liderança política, campo, dados e metas eleitorais.",
      metrics: [
        { label: "Total geral de lideranças", value: "24" },
        { label: "Apoiadores cadastrados", value: "1.240" },
        { label: "Votos declarados", value: "3.200" },
        { label: "Votos validados", value: "2.100" },
        { label: "Índice médio de confiança", value: "7,8" },
        { label: "Regiões prioritárias", value: "8" },
      ],
      insights: ["Maricá segue como prioridade central.", "A validação precisa acompanhar o ritmo de cadastros."],
      progress: { label: "Votos validados sobre declarados", value: 66 },
    },
  ],
  [
    {
      id: "coordenacao",
      title: "Coordenação Geral",
      subtitle: "Integra campo, comunicação, dados e validação.",
      icon: Network,
      tone: "blue",
      count: "5",
      countLabel: "equipes",
      status: "Ativo",
      summary: "Camada de governança da campanha, responsável por coordenar equipes e transformar leitura territorial em ação.",
      metrics: [
        { label: "Equipes operacionais", value: "5" },
        { label: "Frentes ativas", value: "8" },
        { label: "Pendências críticas", value: "2" },
        { label: "Ritmo de atualização", value: "Diário" },
      ],
      insights: ["Boa cadência operacional.", "Priorizar atualização de demandas e validação de listas."],
      progress: { label: "Sincronia operacional", value: 78 },
    },
  ],
  [
    {
      id: "liderancas-rj",
      title: "Lideranças RJ",
      subtitle: "Rede estadual em municípios estratégicos.",
      icon: Users,
      tone: "blue",
      count: "24",
      countLabel: "lideranças",
      status: "Ativo",
      summary: "Rede estadual para ampliar capilaridade fora do município principal e identificar territórios com maior potencial.",
      metrics: [
        { label: "Municípios com atuação", value: "7" },
        { label: "Apoiadores cadastrados", value: "1.240" },
        { label: "Votos validados", value: "2.100" },
        { label: "Município líder", value: "Maricá" },
      ],
      insights: ["Niterói e São Gonçalo aparecem como territórios de expansão.", "A cobertura estadual ainda depende da rede de Maricá."],
      progress: { label: "Cobertura estadual", value: 58 },
    },
    {
      id: "liderancas-marica",
      title: "Lideranças Maricá",
      subtitle: "Base principal por bairro e microárea.",
      icon: Users,
      tone: "emerald",
      count: "21",
      countLabel: "bairros",
      status: "Ativo",
      summary: "Núcleo territorial prioritário da campanha, com leitura por bairro, potencial de apoio e validação de votos.",
      metrics: [
        { label: "Total de lideranças em Maricá", value: "21" },
        { label: "Bairros cobertos", value: "21" },
        { label: "Apoiadores estimados", value: "2.200" },
        { label: "Votos declarados", value: "3.200" },
        { label: "Votos validados", value: "2.100" },
        { label: "Maior potencial", value: "Mariana Costa" },
      ],
      insights: ["Centro tem maior base validada.", "Itaipuaçu concentra lacuna relevante até a meta."],
      progress: { label: "Cobertura territorial", value: 68 },
    },
    {
      id: "liderancas-tematicas",
      title: "Lideranças Temáticas",
      subtitle: "Juventude, saúde, comércio e comunidades.",
      icon: UserCheck,
      tone: "violet",
      count: "9",
      countLabel: "segmentos",
      status: "Atenção",
      summary: "Grupos de atuação por pauta e perfil social para aumentar aderência das ações de campo.",
      metrics: [
        { label: "Segmentos ativos", value: "9" },
        { label: "Ações abertas", value: "18" },
        { label: "Confiança média", value: "Média" },
        { label: "Segmento prioritário", value: "Saúde" },
      ],
      insights: ["Rede temática ainda exige validação de contatos.", "Comércio local tem potencial de multiplicação."],
      progress: { label: "Maturidade da rede", value: 52 },
    },
  ],
  [
    {
      id: "apoiadores",
      title: "Apoiadores",
      subtitle: "Pessoas cadastradas, classificadas e vinculadas.",
      icon: Users,
      tone: "emerald",
      count: "1.240",
      countLabel: "pessoas",
      status: "Ativo",
      summary: "Base de relacionamento da campanha, com classificação política e vínculos com lideranças territoriais.",
      metrics: [
        { label: "Apoiadores cadastrados", value: "1.240" },
        { label: "Simpatizantes", value: "318" },
        { label: "Indecisos", value: "80" },
        { label: "Confirmados", value: "742" },
        { label: "Multiplicadores", value: "55" },
        { label: "Sem endereço completo", value: "126" },
      ],
      insights: ["Confirmados representam a maior parte da base.", "Endereços incompletos reduzem precisão territorial."],
      progress: { label: "Qualidade cadastral", value: 74 },
    },
  ],
  [
    {
      id: "prospeccao",
      title: "Prospecção de Eleitores",
      subtitle: "Funil de contatos até voto validado.",
      icon: Database,
      tone: "amber",
      count: "189",
      countLabel: "novos",
      status: "Atenção",
      summary: "Pipeline de avanço dos contatos, do primeiro registro até confirmação política e voto validado.",
      metrics: [
        { label: "Novos contatos", value: "189" },
        { label: "Primeiro atendimento", value: "78" },
        { label: "Simpatizantes", value: "318" },
        { label: "Apoiadores confirmados", value: "742" },
        { label: "Multiplicadores", value: "55" },
        { label: "Votos validados", value: "2.100" },
      ],
      insights: ["O funil precisa acelerar conversão para voto validado.", "Multiplicadores devem puxar novas indicações por bairro."],
      progress: { label: "Conversão do funil", value: 46 },
    },
  ],
  [
    {
      id: "inteligencia",
      title: "Mapas e Inteligência",
      subtitle: "Leitura de força, lacunas e cobertura.",
      icon: Map,
      tone: "cyan",
      count: "12",
      countLabel: "indicadores",
      status: "Preparado",
      summary: "Camada analítica pronta para receber leituras geoespaciais futuras com dados reais.",
      metrics: [
        { label: "Indicadores ativos", value: "12" },
        { label: "Atualização", value: "Semanal" },
        { label: "Base atual", value: "Mock" },
        { label: "Integração futura", value: "Mapbox" },
      ],
      insights: ["Dados mockados preservam o desenho da operação.", "A arquitetura já prevê PostGIS e Mapbox."],
      progress: { label: "Prontidão técnica", value: 70 },
    },
  ],
  [
    {
      id: "mapa-rj",
      title: "Mapa RJ",
      subtitle: "Municípios com atuação e ranking estadual.",
      icon: MapPin,
      tone: "blue",
      count: "7",
      countLabel: "ativos",
      status: "Ativo",
      summary: "Visão estadual de municípios com atuação, lacunas e ranking de presença territorial.",
      metrics: [
        { label: "Municípios ativos", value: "7" },
        { label: "Sem atuação", value: "5" },
        { label: "Cidade líder", value: "Maricá" },
        { label: "Apoiadores", value: "1.240" },
      ],
      insights: ["Expansão estadual deve focar municípios vizinhos.", "Ranking ajuda a priorizar deslocamento de campo."],
      progress: { label: "Atuação estadual", value: 58 },
    },
    {
      id: "mapa-marica",
      title: "Mapa Maricá",
      subtitle: "Bairros, prioridade, cobertura e votos.",
      icon: MapPin,
      tone: "emerald",
      count: "21",
      countLabel: "bairros",
      status: "Ativo",
      summary: "Leitura local por bairro para orientar agenda, lideranças, apoiadores e metas.",
      metrics: [
        { label: "Bairros cobertos", value: "21" },
        { label: "Bairros críticos", value: "8" },
        { label: "Cobertura média", value: "2,1%" },
        { label: "Votos validados", value: "2.100" },
      ],
      insights: ["Centro está forte.", "Itaipuaçu e Inoã pedem reforço de campo."],
      progress: { label: "Cobertura municipal", value: 68 },
    },
    {
      id: "mapa-calor",
      title: "Mapa de Calor",
      subtitle: "Densidade futura por território e PostGIS.",
      icon: Flame,
      tone: "rose",
      count: "5",
      countLabel: "leituras",
      status: "Preparado",
      summary: "Camada preparada para visualizar concentração de lideranças, apoiadores e votos quando o mapa real entrar.",
      metrics: [
        { label: "Concentração de lideranças", value: "Centro" },
        { label: "Concentração de apoiadores", value: "Centro" },
        { label: "Concentração de votos validados", value: "Centro" },
        { label: "Áreas descobertas", value: "8" },
        { label: "Bairros prioritários", value: "Itaipuaçu, Inoã" },
      ],
      insights: ["Mapa de calor ainda usa leitura mockada.", "Futuro ideal: bairros e pontos com geometria PostGIS."],
      progress: { label: "Prontidão geográfica", value: 62 },
    },
  ],
  [
    {
      id: "comparativo",
      title: "Comparativo Eleitoral",
      subtitle: "Cobertura, distância da meta e potencial.",
      icon: BarChart3,
      tone: "violet",
      count: "21",
      countLabel: "bairros",
      status: "Crítico",
      summary: "Transforma eleitores, cobertura, metas e lacunas em prioridade prática para a operação.",
      metrics: [
        { label: "Eleitores por zona/seção", value: "9.210" },
        { label: "Cobertura da campanha", value: "2,1%" },
        { label: "Distância até a meta", value: "1.220" },
        { label: "Potencial não explorado", value: "Alto" },
        { label: "Prioridade por bairro", value: "Itaipuaçu" },
      ],
      insights: ["A distância até a meta ? o principal alerta.", "A campanha precisa cruzar metas com agenda de campo."],
      progress: { label: "Aderência à meta", value: 38 },
    },
  ],
  [
    {
      id: "zonas",
      title: "Zonas, Seções, Eleitores e Metas",
      subtitle: "Locais de votação, responsáveis e metas.",
      icon: Landmark,
      tone: "slate",
      count: "3",
      countLabel: "zonas",
      status: "Ativo",
      summary: "Conecta a mobilização territorial aos locais de votação, seções e metas eleitorais por área.",
      metrics: [
        { label: "Zonas eleitorais", value: "3" },
        { label: "Seções mapeadas", value: "12" },
        { label: "Eleitores mapeados", value: "9.210" },
        { label: "Meta inicial", value: "590" },
        { label: "Responsáveis definidos", value: "3" },
      ],
      insights: ["Metas por seção ajudam a orientar campo.", "Próximo passo: vincular pessoas aos locais de votação."],
      progress: { label: "Mapeamento eleitoral", value: 64 },
    },
  ],
];
