export type BaseScope = "RJ" | "Maricá" | "São Gonçalo" | "Niterói";

export type TerritoryOption = {
  city: string;
  area: string;
  neighborhoods: string[];
};

export const rjRegions: Record<string, string[]> = {
  Metropolitana: [
    "Belford Roxo",
    "Cachoeiras de Macacu",
    "Duque de Caxias",
    "Guapimirim",
    "Itaboraí",
    "Itaguaí",
    "Japeri",
    "Magé",
    "Maricá",
    "Mesquita",
    "Nilópolis",
    "Niterói",
    "Nova Iguaçu",
    "Paracambi",
    "Petrópolis",
    "Queimados",
    "Rio Bonito",
    "Rio de Janeiro",
    "São Gonçalo",
    "São João de Meriti",
    "Seropédica",
    "Tanguá",
  ],
  "Costa Verde": ["Angra dos Reis", "Mangaratiba", "Paraty"],
  "Médio Paraíba": [
    "Barra do Piraí",
    "Barra Mansa",
    "Itatiaia",
    "Pinheiral",
    "Piraí",
    "Porto Real",
    "Quatis",
    "Resende",
    "Rio Claro",
    "Valença",
    "Volta Redonda",
  ],
  "Centro-Sul Fluminense": [
    "Areal",
    "Comendador Levy Gasparian",
    "Engenheiro Paulo de Frontin",
    "Mendes",
    "Miguel Pereira",
    "Paraíba do Sul",
    "Paty do Alferes",
    "Rio das Flores",
    "Sapucaia",
    "Três Rios",
    "Vassouras",
  ],
  Serrana: [
    "Bom Jardim",
    "Cantagalo",
    "Carmo",
    "Cordeiro",
    "Duas Barras",
    "Macuco",
    "Nova Friburgo",
    "Santa Maria Madalena",
    "São José do Vale do Rio Preto",
    "São Sebastião do Alto",
    "Sumidouro",
    "Teresópolis",
    "Trajano de Moraes",
  ],
  "Baixadas Litorâneas": [
    "Araruama",
    "Armação dos Búzios",
    "Arraial do Cabo",
    "Cabo Frio",
    "Casimiro de Abreu",
    "Iguaba Grande",
    "Rio das Ostras",
    "São Pedro da Aldeia",
    "Saquarema",
    "Silva Jardim",
  ],
  "Norte Fluminense": [
    "Campos dos Goytacazes",
    "Carapebus",
    "Cardoso Moreira",
    "Conceição de Macabu",
    "Macaé",
    "Quissamã",
    "São Fidélis",
    "São Francisco de Itabapoana",
    "São João da Barra",
  ],
  "Noroeste Fluminense": [
    "Aperibé",
    "Bom Jesus do Itabapoana",
    "Cambuci",
    "Italva",
    "Itaocara",
    "Itaperuna",
    "Laje do Muriaé",
    "Miracema",
    "Natividade",
    "Porciúncula",
    "Santo Antônio de Pádua",
    "São José de Ubá",
    "Varre-Sai",
  ],
};

export const cityRegion = Object.fromEntries(
  Object.entries(rjRegions).flatMap(([region, cities]) =>
    cities.map((city) => [city, region]),
  ),
) as Record<string, string>;

export const rjCities = Object.values(rjRegions).flat().sort((a, b) => a.localeCompare(b, "pt-BR"));

export const municipalTerritories: Record<Exclude<BaseScope, "RJ">, Record<string, string[]>> = {
  Maricá: {
    "Sede / Maricá": [
      "Centro",
      "Flamengo",
      "Mumbuca",
      "Itapeba",
      "Parque Nanci",
      "Ponta Grossa",
      "São José do Imbassaí",
      "Araçatiba",
      "Jacaroá",
      "Barra de Maricá",
      "Zacarias",
      "Restinga de Maricá",
      "Retiro",
      "Camburi",
      "Pindobas",
      "Caxito",
      "Ubatiba",
      "Pilar",
      "Lagarto",
      "Silvado",
      "Condado de Maricá",
      "Marquês de Maricá",
    ],
    "Ponta Negra": [
      "Ponta Negra",
      "Jaconé",
      "Cordeirinho",
      "Guaratiba",
      "Jardim Interlagos",
      "Jardim Balneário Bambuí",
      "Pindobal",
      "Caju",
      "Manoel Ribeiro",
      "Espraiado",
      "Vale da Figueira",
      "Bananal",
    ],
    Inoã: ["Inoã", "Chácaras de Inoã", "Calaboca", "SPAR", "Santa Paula", "Cassorotiba"],
    Itaipuaçu: [
      "Recanto de Itaipuaçu",
      "Praia de Itaipuaçu",
      "Morada das Águias",
      "Rincão Mimoso",
      "Barroco",
      "Jardim Atlântico Oeste",
      "Jardim Atlântico Central",
      "Jardim Atlântico Leste",
      "Cajueiros",
      "Itaocaia Valley",
    ],
  },
  "São Gonçalo": {
    "1º Distrito - São Gonçalo / Sede": [
      "Palmeira",
      "Itaoca",
      "Fazenda dos Mineiros",
      "Porto do Rosa",
      "Boaçu",
      "Zé Garoto",
      "Brasilândia",
      "Rosane",
      "Vila Lara",
      "Centro / Rodo de São Gonçalo",
      "Rocha",
      "Lindo Parque",
      "Tribobó",
      "Colubandê",
      "Mutondo",
      "Galo Branco",
      "Estrela do Norte",
      "São Miguel",
      "Mutuá",
      "Mutuaguaçu",
      "Mutuapira",
      "Cruzeiro do Sul",
      "Antonina",
      "Nova Cidade",
      "Trindade",
      "Luiz Caçador",
      "Recanto das Acácias",
      "Itaúna",
      "Salgueiro",
      "Alcântara",
    ],
    "2º Distrito - Ipiíba": [
      "Almerinda",
      "Jardim Nova República",
      "Arsenal",
      "Maria Paula",
      "Arrastão",
      "Anaia Pequeno",
      "Joquei",
      "Coelho",
      "Amendoeira",
      "Jardim Amendoeira",
      "Vila Candoza",
      "Anaia Grande",
      "Ipiíba",
      "Engenho do Roçado",
      "Rio do Ouro",
      "Várzea das Moças",
      "Santa Isabel",
      "Eliane",
      "Ieda",
      "Sacramento",
    ],
    "3º Distrito - Monjolos": [
      "Jardim Catarina",
      "Raul Veiga",
      "Vila Três",
      "Laranjal",
      "Santa Luzia",
      "Bom Retiro",
      "Gebara",
      "Vista Alegre",
      "Lagoinha",
      "Miriambi",
      "Tiradentes",
      "Pacheco",
      "Barracão",
      "Guarani",
      "Monjolo",
      "Marambaia",
      "Largo da Idéia",
    ],
    "4º Distrito - Neves": [
      "Boa Vista",
      "Porto da Pedra",
      "Porto Novo",
      "Gradim",
      "Porto Velho",
      "Neves",
      "Venda da Cruz",
      "Convanca",
      "Vila Lage",
      "Porto da Madama",
      "Paraíso",
      "Patronato",
      "Mangueira",
    ],
    "5º Distrito - Sete Pontes": [
      "Parada 40",
      "Camarão",
      "Santa Catarina",
      "Barro Vermelho",
      "Pita",
      "Zumbi",
      "Tenente Jardim",
      "Morro do Castro",
      "Engenho Pequeno",
      "Novo México",
    ],
  },
  Niterói: {
    "Praias da Baía": [
      "Bairro de Fátima",
      "Boa Viagem",
      "Cachoeiras",
      "Centro",
      "Charitas",
      "Gragoatá",
      "Icaraí",
      "Ingá",
      "Jurujuba",
      "Morro do Estado",
      "Pé Pequeno",
      "Ponta d'Areia",
      "Santa Rosa",
      "São Domingos",
      "São Francisco",
      "Viradouro",
      "Vital Brazil",
    ],
    Norte: [
      "Baldeador",
      "Barreto",
      "Caramujo",
      "Cubango",
      "Engenhoca",
      "Fonseca",
      "Ilha da Conceição",
      "Santa Bárbara",
      "Santana",
      "São Lourenço",
      "Tenente Jardim",
      "Viçoso Jardim",
    ],
    Oceânica: [
      "Cafubá",
      "Camboinhas",
      "Engenho do Mato",
      "Itacoatiara",
      "Itaipu",
      "Jacaré",
      "Jardim Imbuí",
      "Maravista",
      "Piratininga",
      "Santo Antônio",
      "Serra Grande",
    ],
    Pendotiba: [
      "Badu",
      "Cantagalo",
      "Ititioca",
      "Largo da Batalha",
      "Maceió",
      "Maria Paula",
      "Matapaca",
      "Sapê",
      "Vila Progresso",
    ],
    Leste: ["Muriqui", "Rio do Ouro", "Várzea das Moças"],
  },
};

export function getMunicipalNeighborhoods(scope: Exclude<BaseScope, "RJ">) {
  return Object.values(municipalTerritories[scope]).flat();
}

export function getAutomaticArea(scope: BaseScope, city: string, neighborhood: string) {
  if (scope === "RJ") return cityRegion[city] ?? "Região não definida";

  const areas = municipalTerritories[scope];
  const found = Object.entries(areas).find(([, neighborhoods]) => neighborhoods.includes(neighborhood));
  return found?.[0] ?? "Área não definida";
}
