import type { BaseEleitoralDataset } from "./types";

const now = "2026-06-04";

const audit = {
  createdAt: "2026-05-20",
  updatedAt: now,
  createdByUserId: "usr-1",
  updatedByUserId: "usr-1",
};

export const mockDataset: BaseEleitoralDataset = {
  usuarios: [
    {
      id: "usr-1",
      nome: "Coordenação Geral",
      email: "coordenacao@base360.local",
      telefone: "(21) 99900-0001",
      papel: "admin",
      status: "ativo",
      avatarUrl: null,
      ...audit,
    },
    {
      id: "usr-2",
      nome: "Equipe Territorial Maricá",
      email: "territorial@base360.local",
      telefone: "(21) 99900-0002",
      papel: "coordenador",
      status: "ativo",
      avatarUrl: null,
      ...audit,
    },
  ],
  regioes: [
    {
      id: "reg-1",
      nome: "Maricá Estratégica",
      tipo: "estrategica",
      municipioId: "mun-marica",
      prioridade: "alta",
      responsavelUserId: "usr-2",
      geometria: null,
      ...audit,
    },
    {
      id: "reg-2",
      nome: "Leste RJ",
      tipo: "municipal",
      municipioId: null,
      prioridade: "media",
      responsavelUserId: "usr-1",
      geometria: null,
      ...audit,
    },
  ],
  municipios: [
    {
      id: "mun-marica",
      nome: "Maricá",
      uf: "RJ",
      codigoIbge: "3302700",
      regiaoId: "reg-1",
      comAtuacao: true,
      eleitoresEstimados: 125000,
      geometria: null,
      ...audit,
    },
    {
      id: "mun-niteroi",
      nome: "Niterói",
      uf: "RJ",
      codigoIbge: "3303302",
      regiaoId: "reg-2",
      comAtuacao: true,
      eleitoresEstimados: 390000,
      geometria: null,
      ...audit,
    },
  ],
  bairros: [
    {
      id: "bai-centro",
      nome: "Centro",
      municipioId: "mun-marica",
      regiaoId: "reg-1",
      prioridade: "media",
      eleitoresEstimados: 12000,
      coberturaPercentual: 5,
      geometria: null,
      ...audit,
    },
    {
      id: "bai-itaipuacu",
      nome: "Itaipuaçu",
      municipioId: "mun-marica",
      regiaoId: "reg-1",
      prioridade: "alta",
      eleitoresEstimados: 28000,
      coberturaPercentual: 1.25,
      geometria: null,
      ...audit,
    },
    {
      id: "bai-inoa",
      nome: "Inoã",
      municipioId: "mun-marica",
      regiaoId: "reg-1",
      prioridade: "alta",
      eleitoresEstimados: 18000,
      coberturaPercentual: 1.22,
      geometria: null,
      ...audit,
    },
  ],
  liderancas: [
    {
      id: "lid-1",
      nome: "Mariana Costa",
      apelido: "Mari da Saúde",
      telefone: "(21) 99911-2401",
      email: "mariana.costa@base360.local",
      tipoLideranca: "comunitaria",
      status: "ativo",
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      regiaoId: "reg-1",
      responsavelUserId: "usr-2",
      apoiadoresCadastrados: 186,
      apoiadoresEstimadosDiretos: 260,
      apoiadoresEstimadosIndiretos: 410,
      votosDeclarados: 520,
      votosValidados: 368,
      grauConfianca: "alto",
      fonteEstimativa: "Lista validada em reunião",
      comprovacao: "Planilha e fotos de encontro",
      ultimaAtualizacao: "2026-06-03",
      proximaAcao: "Reunião com comerciantes",
      observacoes: "Boa entrada com lideranças de bairro.",
      ...audit,
    },
    {
      id: "lid-2",
      nome: "Rafael Almeida",
      apelido: "Rafa Inoã",
      telefone: "(21) 99820-1140",
      email: "rafael.almeida@base360.local",
      tipoLideranca: "juventude",
      status: "ativo",
      municipioId: "mun-marica",
      bairroId: "bai-inoa",
      regiaoId: "reg-1",
      responsavelUserId: "usr-2",
      apoiadoresCadastrados: 112,
      apoiadoresEstimadosDiretos: 180,
      apoiadoresEstimadosIndiretos: 260,
      votosDeclarados: 310,
      votosValidados: 208,
      grauConfianca: "medio",
      fonteEstimativa: "Grupos de WhatsApp",
      comprovacao: "Lista parcial",
      ultimaAtualizacao: "2026-06-02",
      proximaAcao: "Mutirão de cadastro",
      observacoes: "Potencial de crescimento rápido.",
      ...audit,
    },
  ],
  apoiadoresPessoas: [
    {
      id: "pes-1",
      nome: "João Pereira",
      telefone: "(21) 98811-2210",
      email: null,
      documento: null,
      dataNascimento: null,
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      endereco: null,
      liderancaId: "lid-1",
      tipoPessoa: "apoiador",
      statusPolitico: "apoiador_confirmado",
      nivelConfianca: "alto",
      nivelPrecisaoGeografica: "bairro",
      localVotacaoId: "loc-1",
      secaoEleitoralId: "sec-102",
      dataUltimoContato: "2026-06-02",
      proximaAcao: "Convidar para reunião",
      responsavelUserId: "usr-2",
      coordenadas: null,
      ...audit,
    },
    {
      id: "pes-2",
      nome: "Ana Luiza Santos",
      telefone: "(21) 97770-8820",
      email: "ana.santos@base360.local",
      documento: null,
      dataNascimento: null,
      municipioId: "mun-marica",
      bairroId: "bai-inoa",
      endereco: null,
      liderancaId: "lid-2",
      tipoPessoa: "voluntario",
      statusPolitico: "multiplicador",
      nivelConfianca: "alto",
      nivelPrecisaoGeografica: "rua",
      localVotacaoId: "loc-2",
      secaoEleitoralId: "sec-134",
      dataUltimoContato: "2026-06-03",
      proximaAcao: "Organizar caminhada",
      responsavelUserId: "usr-2",
      coordenadas: null,
      ...audit,
    },
  ],
  prospeccao: [
    {
      id: "pro-1",
      nome: "Patrícia Lima",
      telefone: "(21) 95510-2001",
      email: null,
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      origem: "campo",
      etapa: "novo_contato",
      prioridade: "media",
      responsavelUserId: "usr-2",
      liderancaIndicadoraId: null,
      dataContato: "2026-06-03",
      proximaAcao: "Primeiro atendimento",
      observacoes: null,
      ...audit,
    },
    {
      id: "pro-2",
      nome: "Bruno Teixeira",
      telefone: "(21) 98830-4402",
      email: null,
      municipioId: "mun-marica",
      bairroId: "bai-itaipuacu",
      origem: "whatsapp",
      etapa: "simpatizante",
      prioridade: "alta",
      responsavelUserId: "usr-2",
      liderancaIndicadoraId: "lid-1",
      dataContato: "2026-06-02",
      proximaAcao: "Validar voto",
      observacoes: "Contato indicado por liderança local.",
      ...audit,
    },
  ],
  zonasEleitorais: [
    {
      id: "zon-55",
      numero: "55",
      municipioId: "mun-marica",
      nome: "Zona 55 - Maricá",
      totalEleitores: 125000,
      metaVotos: 6500,
      votosEstimados: 4100,
      votosValidados: 2100,
      prioridade: "alta",
      responsavelUserId: "usr-2",
      ...audit,
    },
  ],
  locaisVotacao: [
    {
      id: "loc-1",
      nome: "C.E. Elisiário Matta",
      endereco: "Rua Álvares de Castro, Centro",
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      zonaEleitoralId: "zon-55",
      totalEleitores: 2810,
      coordenadas: null,
      ...audit,
    },
    {
      id: "loc-2",
      nome: "CIEP Inoã",
      endereco: "Estrada de Inoã",
      municipioId: "mun-marica",
      bairroId: "bai-inoa",
      zonaEleitoralId: "zon-55",
      totalEleitores: 2980,
      coordenadas: null,
      ...audit,
    },
  ],
  secoesEleitorais: [
    {
      id: "sec-102",
      numero: "102",
      zonaEleitoralId: "zon-55",
      localVotacaoId: "loc-1",
      totalEleitores: 2810,
      historicoVotacao: "Alta participação",
      metaVotos: 180,
      votosEstimados: 210,
      votosValidados: 124,
      ...audit,
    },
    {
      id: "sec-134",
      numero: "134",
      zonaEleitoralId: "zon-55",
      localVotacaoId: "loc-2",
      totalEleitores: 2980,
      historicoVotacao: "Crescimento recente",
      metaVotos: 190,
      votosEstimados: 160,
      votosValidados: 76,
      ...audit,
    },
  ],
  demandas: [
    {
      id: "dem-1",
      titulo: "Fila de consulta especializada",
      pessoaId: "pes-1",
      liderancaId: "lid-1",
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      tipoDemanda: "saude",
      prioridade: "alta",
      status: "em_atendimento",
      responsavelUserId: "usr-2",
      dataRetorno: "2026-06-07",
      observacoes: "Acompanhar retorno com a equipe de campo.",
      ...audit,
    },
  ],
  agendaCampo: [
    {
      id: "age-1",
      titulo: "Reunião com lideranças do Centro",
      tipo: "reuniao",
      data: "2026-06-06",
      horario: "19:00",
      municipioId: "mun-marica",
      bairroId: "bai-centro",
      liderancaId: "lid-1",
      responsavelUserId: "usr-1",
      status: "confirmado",
      observacoes: "Validar lista de novos apoiadores.",
      ...audit,
    },
  ],
  metricasDashboard: {
    totalLiderancas: 24,
    totalApoiadores: 1240,
    apoiadoresEstimados: 2200,
    votosDeclarados: 3200,
    votosValidados: 2100,
    indiceConfianca: 7.8,
    municipiosAtuacao: 5,
    bairrosCobertos: 21,
    zonasEleitorais: 3,
    regioesPrioritarias: 8,
    evolucaoSemanal: [
      { semana: "Sem 1", cadastros: 45, liderancas: 3, apoiadores: 42 },
      { semana: "Sem 2", cadastros: 78, liderancas: 5, apoiadores: 73 },
      { semana: "Sem 3", cadastros: 95, liderancas: 7, apoiadores: 88 },
      { semana: "Sem 4", cadastros: 133, liderancas: 9, apoiadores: 124 },
    ],
    rankingLiderancas: [
      { id: "lid-1", nome: "Mariana Costa", valor: 368, secundario: 520 },
      { id: "lid-2", nome: "Rafael Almeida", valor: 208, secundario: 310 },
    ],
    rankingBairros: [
      { id: "bai-centro", nome: "Centro", valor: 600, secundario: 420 },
      { id: "bai-itaipuacu", nome: "Itaipuaçu", valor: 350, secundario: 180 },
      { id: "bai-inoa", nome: "Inoã", valor: 220, secundario: 130 },
    ],
    comparativoEleitoral: [
      {
        bairroId: "bai-centro",
        bairro: "Centro",
        eleitores: 12000,
        apoiadoresCadastrados: 600,
        votosValidados: 420,
        cobertura: 5,
        meta: 600,
        distanciaMeta: 180,
        prioridade: "media",
      },
      {
        bairroId: "bai-itaipuacu",
        bairro: "Itaipuaçu",
        eleitores: 28000,
        apoiadoresCadastrados: 350,
        votosValidados: 180,
        cobertura: 1.25,
        meta: 1400,
        distanciaMeta: 1220,
        prioridade: "alta",
      },
    ],
    distribuicaoStatusPolitico: {
      indefinido: 80,
      simpatizante: 420,
      apoiador_confirmado: 760,
      multiplicador: 55,
      voto_validado: 2100,
      oposicao: 18,
    },
  },
};
